### ISSUE TITLE
lammps cuda12 throws CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by hsulab** [tummfm/chemtrain-deploy#4]
Dear Developer,

Many thanks for building this amazing package. I have successfully compiled the chemtrain-depoly and can run my own model using the cpu device. However, there is error when cuda12 is used, which is

```
Connector constructor
[JCN:INFO] Loaded PJRT plugin cuda12
E1029 04:22:28.443937 1898682 cuda_dnn.cc:534] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E1029 04:22:28.443991 1898682 cuda_dnn.cc:538] Memory usage: 33820770304 bytes free, 42405855232 bytes total.
E1029 04:22:28.444264 1898682 cuda_dnn.cc:534] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E1029 04:22:28.444286 1898682 cuda_dnn.cc:538] Memory usage: 33820770304 bytes free, 42405855232 bytes total.
2025-10-29 04:22:28.444405: I external/xla/xla/pjrt/pjrt_c_api_client.cc:127] PjRtCApiClient created.
[JCN:INFO] Found devices [CudaDevice(id=0),]
[JCN:INFO] Initialize SimpleSparseNeighborList
[JCN:INFO] Use half list only 1
[JCN:INFO] Model properties:
        -Cutoff: 6.000000
        -Com. distance: 6.000000
        -Unit style: metal
```

And I am using python3.10 with jax 0.4.36

```
jax                       0.4.36                   pypi_0    pypi
jax-cuda12-pjrt           0.4.36                   pypi_0    pypi
jax-cuda12-plugin         0.4.36                   pypi_0    pypi
jaxlib                    0.4.36                   pypi_0    pypi
nvidia-cublas-cu12        12.6.0.22                pypi_0    pypi
nvidia-cuda-cupti-cu12    12.6.37                  pypi_0    pypi
nvidia-cuda-nvcc-cu12     12.9.86                  pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.6.20                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.6.37                  pypi_0    pypi
nvidia-cudnn-cu12         9.11.0.98                pypi_0    pypi
nvidia-cufft-cu12         11.2.6.28                pypi_0    pypi
nvidia-cusolver-cu12      11.6.4.38                pypi_0    pypi
nvidia-cusparse-cu12      12.5.2.23                pypi_0    pypi
nvidia-ml-py              12.555.43                pypi_0    pypi
nvidia-nccl-cu12          2.22.3                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.20                  pypi_0    pypi
nvidia-nvshmem-cu12       3.4.5                    pypi_0    pypi
```

I wonder if this is due to the mismatch in the cudnn version between the conda environment and the installed one on the cluster gpu node.

Any advice will be helpful!

All the best,
Jiayan

**Comment by pl-fuchs** [comment]
Thank you for sharing the issue.

I believe I have encountered a similar problem when cuDNN was not installed. How did you compile the plugin? Did you compile the pjrt library yourself?

**Comment by hsulab** [comment]
Many thanks for the reply.

I fixed the issue, and it seems to work well.

There is no installed cuDNN on our GPU nodes. So I simply use the pjrt from the jax in my conda environment. I finally realised the cudnn in conda is not in the standard $CONDA_PREFIX/lib. Once I add $CONDA_PREFIX/lib/python3.x/site-packages/nvidia/cudnn/lib to LD_LIBRARY_PATH, the calculation finished with some warnings like `ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_511', 20 bytes spill stores, 20 bytes spill loads`. Also, some forces differ from CPU results after four decimals, I guess this is acceptable.

I think we may close this issue if there are no more concerns.
